name: Development build

on:
  pull_request:
    branches-ignore:
      - 'l10n_main'
    types: [opened, reopened]
  push:
    branches-ignore:
      - 'l10n_main'
  workflow_dispatch:

jobs:
  build:
    name: Development build
    strategy:
      matrix:
        include:
          - platform: 2
            platform_name: ios

    runs-on: macos-14

    steps:
      - name: Select Xcode 15.4
        run: |
          sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
          xcodebuild -version || true

      - name: Install GNU Make
        run: |
          brew update
          brew install make

      - name: Install Java 8 (Temurin) via Homebrew
        run: |
          brew install --cask temurin@8 || true

      - name: Install ldid
        run: |
          brew install ldid || true

      - name: Remove work folders
        run: |
          echo "before"
          ls -lah ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          echo "after"
          ls -lah ./

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout repository submodules
        run: git submodule update --init --recursive

      - name: Build for ${{ matrix.platform_name }}
        env:
          IPHONEOS_DEPLOYMENT_TARGET: 14.0
        run: |
          set -o pipefail
          export PATH=/opt/homebrew/bin:$PATH
          export SLIMMED=0

          if [ "${{ matrix.platform_name }}" == "ios" ]; then
            gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }}

            gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }} TROLLSTORE_JIT_ENT=1

          elif [ "${{ matrix.platform_name }}" == "tvos" ]; then
            gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }} TROLLSTORE_JIT_ENT=1

          else
            gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }}
          fi

      - name: Upload regular ipa
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: org.angelauramc.amethystremastered-${{ matrix.platform_name }}.ipa
          path: artifacts/org.angelauramc.amethystremastered-*-${{ matrix.platform_name }}.ipa

      - name: Upload regular tipa
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: org.angelauramc.amethystremastered-${{ matrix.platform_name }}-trollstore.tipa
          path: artifacts/org.angelauramc.amethystremastered-*-${{ matrix.platform_name }}-trollstore.tipa

      - name: Upload PojavLauncher.dSYM
        if: matrix.platform_name == 'ios' && success()
        uses: actions/upload-artifact@v4
        with:
          name: AngelAuraAmethyst.dSYM
          path: artifacts/AngelAuraAmethyst.dSYM